---
- name: Backup Cisco Router Configuration
  hosts: cisco_routers
  gather_facts: no
  vars:
    ansible_user: "{{ router_user }}"
    ansible_password: "{{ router_pass }}"

  tasks:
    - name: Back up running config
      cisco.ios.ios_config:
        backup: yes
      register: backup_output

    - name: Show where the backup is stored
      debug:
        msg: "Backup saved at: {{ backup_output.backup_path }}"
