  tasks:

    - name: Check if winrm is available
      win_shell: |
        if (Get-Command winrm -ErrorAction SilentlyContinue) {
            Write-Output "Present"
        } else {
            Write-Output "Missing"
        }
      register: winrm_check

    - name: Ensure WinRM is configured (only if winrm is installed)
      win_shell: winrm quickconfig -q
      when: winrm_check.stdout is search("Present")
      register: winrm_config_result
      ignore_errors: yes

    - name: Debug WinRM output (optional)
      debug:
        var: winrm_config_result.stdout
      when: winrm_config_result is defined

    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy update script to remote machine
      win_copy:
        content: "{{ update_script_content }}"
        dest: "{{ update_script_path }}"

    - name: Register and start scheduled task for update
      win_scheduled_task:
        name: "{{ update_task_name }}"
        description: "Run PSWindowsUpdate and reboot if needed"
        actions:
          - path: powershell.exe
            arguments: "-ExecutionPolicy Bypass -File '{{ update_script_path }}'"
        triggers: []
        run_now: yes
        username: SYSTEM
        run_level: highest
        state: present
        enabled: yes
