---
- hosts: windows
  become: true
  tasks:
    - win_updates:
        state: latest
        action: check
      ignore_errors: true
      register: check_result

    - win_updates:
        state: latest
        action: install
      when: check_result.results | sum > 0
